### ISSUE TITLE
Crimea geometry

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data-admin-xx#15]
Regarding purely the geometries (and not the politics!), there are two copies of Crimea with differing shapes, to my eye `85688855` appears to be closer than `1159339547` to the basemap.

If these two places are in fact coterminous, would it be worth selecting the 'better' geom and using that for both records?

- https://github.com/whosonfirst-data/whosonfirst-data-admin-ua/blob/master/data/856/888/55/85688855.geojson
- https://github.com/whosonfirst-data/whosonfirst-data-admin-xx/blob/master/data/115/933/954/7/1159339547.geojson

**Comment by thisisaaronland** [comment]
Those are two different placetypes. The `region` placetype is parented by the `disputed` placetype. The `disputed` placetype is parented by two countries. Crimea is one of those places at the intersection of cartography and reality, and until things change the geometries and the politics will remain intertwined.

**Comment by missinglink** [comment]
Politics aside, I don't think 1159339547 is accurate, looking at the southern boundary you can see how the shape differs significantly from the basemap.

![Screenshot_20210908-182256](https://user-images.githubusercontent.com/738069/132547818-a4f5aab3-79ac-4b17-a867-a60236695cb6.png)

I'm not proposing merging these two disparate places, just questioning why the geometries differ and if one is superior to the other.

**Comment by missinglink** [comment]
I might be wrong but I was assuming that since it's a peninsula that the coastal boundary would serve as the geometry boundary.

**Comment by stepps00** [comment]
https://github.com/whosonfirst-data/whosonfirst-data/issues/1930 was opened to track the creation of "world view" geometries in WOF.. that work is chugging along slowly, but once merged, should correct geometry and parenting issues in/around Crimea.

The geometry for 1159339547 has been [updated in the branch](https://github.com/whosonfirst-data/whosonfirst-data-admin-xx/blob/stepps00/disputed-updates/data/115/933/954/7/1159339547.geojson) I've opened with those updates, which does correct these coastal boundary issues.

I'll comment in that issue when I have an update, which I hope to be very soon..

**Comment by missinglink** [comment]
Agh cool, I saw that issue but didn't see the updated geom, looks much better.

I'm happy to close this in favour of 1930
